---
# this file contains main list of tasks to be executed by the elm role
# tasks file for elm-role
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  with_items: "{{ elm_dependencies }}"
  tags:
    - configuration

- name: add elm and compile it from source
  shell: wget "https://github.com/elm/compiler/release/download/0.19.0/binaries-for-linux.tar.gz"
  args:
    creates: /etc/apt/source.list.d/elmsourse.list
  tags:
    - confuguration

- name: unpack elm binaries
  shell: tar xzf binaries-for-linux.tar.gz
  args:
    creates: /etc/apt/source.list.d/elmunpacksource.list
  tags:
    - confuguration

- name: move elm to bin
  shell: sudo mv /usr/local/bin/
  tags:
    - configuration

- name: setup elm project
  shell: elm init
  tags:
    - configuration

- name: install additional elm packages
  elm:
    state: "{{ elm_install_state }}"
    name: "{{ item.name }}"
  with_items: "{{ elm_packages }}"
  tags:
    - configuration
